<?php

use Illuminate\Support\Facades\Artisan;
use Tests\TestCase;

uses(TestCase::class);

/*
 * Every compiled registry artifact still matches what its builder produces.
 *
 * ## Why this exists
 *
 * `resources/registry/*.json` are GENERATED files that are also COMMITTED,
 * because production has no sibling repos to compile from. That combination has
 * one failure mode and it is silent: the generator is not re-run, the committed
 * artifact drifts from its source, and **a stale artifact looks exactly like a
 * current one**. Nothing anywhere reports it.
 *
 * It had already happened. `fancy-devtools` was registered, built and shipped,
 * and `readmes.json` was never rebuilt — so the package went live with no README
 * on the docs site, and two flow READMEs served content months out of date. It
 * was found by accident, months later, because running the test suite happened
 * to regenerate the file and left it dirty in `git status`.
 *
 * This is the same class as `SubmodulesAreRegisteredTest` — a fact about the
 * repo that no code path asserts — except that there was no check here at all
 * rather than one nobody stood at.
 *
 * ## How it works, and why it runs the real builder
 *
 * Each case runs the actual artisan command, compares the bytes, then restores
 * the file. It deliberately does NOT reimplement the compile step: a second copy
 * of the payload shape and the json_encode flags would be one more thing to
 * drift, which is the exact defect being guarded. The cost is that these tests
 * write to `resources/registry/` while running; every one restores in a
 * `finally`.
 *
 * ## Why three of these are envelope-scoped and one is not
 *
 * `registry`, `readmes` and `tui-previews` compile from SIBLING repos
 * (`dirname(base_path()).'/<slug>'`), so they only work where the envelope is
 * checked out — see the note in `SubmodulesAreRegisteredTest`. Worse than not
 * working: `ReadmeSource` falls back to `node_modules/` and `vendor/`, which DO
 * exist in the app's CI, so running it there would compile a different, smaller
 * artifact and fail for a reason that has nothing to do with staleness.
 *
 * `flow-nodes` is different and deliberately ungrouped. It compiles from
 * `resource_path('flow-nodes')` — inside this repo, because a marketplace node
 * is vendored source rather than a package. It has all its inputs in a
 * single-repo checkout, so it runs on every push, where the feedback is fastest.
 *
 * `connectors.json` is absent from this file on purpose: it is generated by
 * weaver.agi, not by any command here, so there is nothing to re-run.
 * `connectors:check` is what guards it.
 */

/**
 * Assert that re-running `$command` reproduces the committed artifact exactly.
 */
function expectCompiledArtifactIsCurrent(string $command, string $path): void
{
    expect(is_file($path))->toBeTrue("{$path} is missing; run `php artisan {$command}`");

    $before = (string) file_get_contents($path);

    // The vacuity guard. Comparing a file to itself proves nothing if both
    // sides are empty, and an artifact this small is not a real one.
    expect(strlen($before))->toBeGreaterThan(500, "{$path} is too small to be a real artifact");

    try {
        $exit = Artisan::call($command);

        // Asserted BEFORE the comparison, and that order is load-bearing. Every
        // one of these builders refuses and writes NOTHING when its source is
        // missing — so on failure the file is untouched, `after === before`, and
        // a content-only check would pass having verified nothing at all.
        expect($exit)->toBe(0, "`php artisan {$command}` failed, so staleness could not be determined:\n".Artisan::output());

        $after = (string) file_get_contents($path);

        // Compared as a boolean rather than `toBe($before)` on purpose: these
        // artifacts run to megabytes, and a failure diff of two of them buries
        // the one line that says what to do.
        expect($after === $before)->toBeTrue(implode("\n", [
            basename($path).' is STALE — rebuilding it produces different bytes.',
            '',
            sprintf('  committed: %d bytes', strlen($before)),
            sprintf('  rebuilt:   %d bytes', strlen($after)),
            '',
            "Fix: run `php artisan {$command}` and commit the result.",
            '',
            'This is generated and committed, so production serves whatever was',
            'last committed. Until it is rebuilt, the site is serving content that',
            'no longer matches the source it was compiled from — and nothing else',
            'reports that, because a stale artifact looks exactly like a fresh one.',
        ]));
    } finally {
        // Restore unconditionally. The builders write in place, so a failure
        // here must not leave the working tree dirty and send the next person
        // chasing a change nobody made.
        file_put_contents($path, $before);
    }
}

it('has a current component registry', function () {
    expectCompiledArtifactIsCurrent('registry:build', resource_path('registry/registry.json'));
})->group('envelope');

it('has current compiled READMEs', function () {
    expectCompiledArtifactIsCurrent('readmes:build', resource_path('registry/readmes.json'));
})->group('envelope');

it('has current fancy-tui previews', function () {
    expectCompiledArtifactIsCurrent('tui:build', resource_path('registry/tui-previews.json'));
})->group('envelope');

// Ungrouped: its source lives in this repo, so it runs on every push.
it('has a current flow node marketplace', function () {
    expectCompiledArtifactIsCurrent('flow:build', resource_path('registry/flow-nodes.json'));
});
