import type { ComponentDoc } from "./types";
import { Card, Heading, Text } from "@particle-academy/react-fancy";

export const screenDoc: ComponentDoc = {
    intro: (
        <p>
            A registered screen — names a slice of your app for the agent layer. Two modes:
            <strong> JSX children</strong> for hand-built screens, or <strong>schema</strong>{" "}
            for agent-emitted JSON descriptions that render via a component registry. Either
            way the screen registers itself with <code>ScreenSystem</code> and inherits
            agent-presence highlighting.
        </p>
    ),
    examples: [
        {
            name: "JSX children",
            description: "Drop your own JSX. The screen still registers under `id` so agents can target it.",
            render: () => (
                <Card padding="md" className="w-full">
                    <Heading size="sm">dashboard</Heading>
                    <Text size="sm" className="mt-1">A normal Screen with hand-written JSX content.</Text>
                </Card>
            ),
            code: `<Screen id="dashboard" title="Dashboard">
    <Card>
        <Heading>Dashboard</Heading>
        <KpiTile />
        <RecentActivity />
    </Card>
</Screen>`,
        },
        {
            name: "Schema-driven",
            description: "Pass `schema` to render an agent-emitted JSON description via the component registry.",
            render: () => (
                <Text size="sm" className="!text-zinc-500">
                    Register components once with <code>registerFancyComponents()</code>, then any{" "}
                    <code>type</code> in the schema renders via that lookup.
                </Text>
            ),
            code: `<Screen
    id="agent-dashboard"
    title="Generated by Researcher"
    schema={{
        type: "Card",
        children: [
            { type: "Heading", props: { children: "Welcome back" } },
            { type: "Text", props: { children: "Three things are on fire today." } },
        ],
    }}
/>`,
        },
        {
            name: "Pair with a Zustand store",
            description: "Register a per-screen store via `useRegisterStore` from a child — it shows up as `${screen.id}.<name>` in the system map.",
            render: () => (
                <Text size="sm" className="!text-zinc-500">
                    Consumers bring their own Zustand stores. The registry doesn't impose state-shape.
                </Text>
            ),
            code: `import { create } from "zustand";
import { Screen, useRegisterStore } from "@particle-academy/fancy-screens";

const useDashboardStore = create(() => ({ filters: {} }));

function DashboardBody() {
    useRegisterStore("filters", useDashboardStore);
    return <Card>…</Card>;
}

<Screen id="dashboard">
    <DashboardBody />
</Screen>`,
        },
    ],
    props: [
        { name: "id", type: `string`, default: "—", description: "Globally unique screen id. Doubles as the store-key prefix. Required." },
        { name: "title", type: `string`, default: "—", description: "Human-readable title surfaced via `useScreens()`." },
        { name: "children", type: `ReactNode`, default: "—", description: "JSX content. When both `children` and `schema` are provided, children wins." },
        { name: "schema", type: `ScreenSchema`, default: "—", description: "JSON description rendered via the component registry. LLM-friendly — arrays of objects, primitives, discriminated unions." },
        { name: "className", type: `string`, default: "—", description: "Extra classes on the screen wrapper." },
    ],
    notes: (
        <p className="text-xs text-zinc-600 dark:text-zinc-300">
            <strong>Agent presence:</strong> when an MCP bridge tied to this screen mutates
            something, the screen wrapper gets a <code>.agent-focused-element</code> class so
            cross-screen presence is visible without extra wiring.
        </p>
    ),
};
