<?php

namespace App\Support;

/**
 * Editorial Why / What / How for each *package* detail page — the package-level
 * sibling of {@see ComponentContext}. Hand-curated entries live in
 * {@see ENTRIES}; a generated JSON sidecar (written by the docs workflow) fills
 * the rest. Hand-curated always wins on a key collision.
 *
 * Why  — the gap in the ecosystem this package fills; why you&apos;d reach for it.
 * What — the shape of the package: its primitives, its contract, its surface.
 * How  — install + the smallest "first render" so a reader can start.
 *
 * Keyed by package slug.
 */
class PackageContext
{
    /** @var array<string, array{why: string, what: string, how: string}> */
    private const ENTRIES = [
        'fancy-diff' => [
            'why' => 'Reviewing and accepting changes is the human&apos;s job in a Human+ app — and the changes increasingly come from an <em>agent</em> that drafts an edit and waits for a person to confirm it. That is the trust-but-verify loop: agents propose, humans accept or reject, hunk by hunk. Every team rebuilds this surface and most ship a read-only diff with no acceptance, or bolt acceptance onto opaque DOM an embedded agent can&apos;t drive. <code>fancy-diff</code> closes the gap with a controlled, client-side diff viewer where a human and an agent operate the <em>same</em> acceptance state — no server processing, no third-party runtime deps, and no DOM scraping.',
            'what' => 'A React side-by-side (or inline) document diff viewer with per-hunk accept/reject and a live merged result. The diff engine — line-level LCS plus intra-line word/char segments — runs in-browser, in-house, with <strong>zero third-party runtime dependencies</strong>. Acceptance is controlled: <code>value</code> is a <code>Record&lt;hunkId, "accepted" | "rejected" | "pending"&gt;</code> map with <code>onChange</code>; <code>getMergedResult()</code> / <code>onResult</code> fold the diff and acceptance into the merged document. The <code>source</code> is a JSON-friendly discriminated union with <strong>three datasources</strong>: <code>{ before, after }</code> (compute the diff in-house), <code>{ unified }</code> (parse a git unified diff), or <code>{ diff }</code> (a pre-built structured <code>Diff</code>). It composes react-fancy primitives (toolbar, buttons, badges, cards), exposes stable <code>data-fancy-diff-hunk</code> handles plus render-prop slots (<code>renderHunk</code> / <code>renderToolbar</code> / <code>renderGutter</code>), supports <code>mode="split" | "inline"</code> and trust-but-verify <code>pendingMode</code>, and emits optional <code>AutoActivity</code> events through <code>@particle-academy/fancy-auto-common</code>. <strong>Git-diff caveat:</strong> a unified diff carries only the changed hunks plus a little context, so parsed files are flagged <code>partial</code> and the merged result reconstructs only the lines in the diff window — feed full <code>{ before, after }</code> documents when you need a fully merged file.',
            'how' => 'Install <code>npm i @particle-academy/fancy-diff</code> (peers: <code>react</code>, <code>react-dom</code>, <code>@particle-academy/react-fancy</code>) and import the stylesheet: <code>import { FancyDiff } from "@particle-academy/fancy-diff"; import "@particle-academy/fancy-diff/styles.css";</code>. Diff two documents: <code>&lt;FancyDiff source={{ before, after }} value={value} onChange={setValue} onResult={(r) =&gt; setMerged(r.text)} /&gt;</code>. Parse a git diff instead: <code>&lt;FancyDiff source={{ unified }} mode="inline" /&gt;</code>. Read the merged document imperatively via a ref — <code>ref.current.getMergedResult().text</code> — and turn on <code>pendingMode</code> so an embedded agent stages proposals a human confirms. A one-sitting MCP bridge maps <code>diff_accept_hunk</code> / <code>diff_reject_hunk</code> onto the same controlled <code>value</code>/<code>onChange</code> loop.',
        ],

        'fancy-pixel' => [
            'why' => 'A site built with Fancy UI wants to <em>prove</em> it — that&apos;s how it earns a listing in the public Showcase, and how the suite stays visible across the web. <code>fancy-pixel</code> is the embeddable badge that does the proving — and the <strong>data pipe</strong> in the same chip: one embed verifies the site <em>and</em> streams its interaction analytics (clicks, scroll, focus heatmaps) to a host&apos;s endpoint, keyed by <code>siteKey</code>. That is how external sites feed a hosting project — the Showcase + the coming Analytics Suite — while a project measuring itself reaches for <code>fancy-heuristics</code> directly. The hard part most badges get wrong is that the host page can simply hide them with one CSS rule — so verification is meaningless. fancy-pixel renders into an <strong>open Shadow DOM</strong> (host CSS can&apos;t reach in), confirms with an <code>IntersectionObserver</code> that it is <em>actually</em> on-screen, and only counts a page as seen once it is. And because the suite is Human+, the badge is <em>inhabitable</em>: it carries a stable handle and dispatches a shown event so an embedded agent reads its presence and state without scraping the DOM.',
            'what' => 'A zero-dependency, vanilla-TypeScript embeddable badge + liveness/collection beacon with <strong>three styles × two placement modes</strong>. <code>style</code> ∈ <code>badge</code> ("Powered by Fancy UI" wordmark + glyph) / <code>mark</code> (glyph only) / <code>beacon</code> (a pulsing dot); <code>mode</code> ∈ <code>placed</code> (inline at a <code>target</code> selector/element) / <code>floating</code> (<code>position: fixed</code> in a corner). Every style renders into an <strong>open Shadow DOM</strong> so host CSS cannot hide it, and emits the <code>data-fancy-badge</code> marker the Showcase scanner detects plus a stable <code>data-fancy-pixel</code> handle and <code>data-fancy-pixel-style</code>. An <code>IntersectionObserver</code> verifies genuine on-screen visibility and dispatches a <code>fancy-pixel:shown</code> <code>CustomEvent</code> on <code>document</code>. The API is one call — <code>mountPixel({ style, mode, target?, siteKey, endpoint?, href? })</code> → a <code>{ host, visible, destroy() }</code> handle — or a single <code>&lt;script&gt;</code> tag that loads <em>and</em> auto-inits from its own <code>data-*</code> attributes (the IIFE global build also exposes <code>window.FancyPixel.mountPixel</code>). <strong>One endpoint, full pipe (opt-in):</strong> set <code>endpoint</code> and the single embed renders the badge, POSTs the verification/liveness ping to <code>${endpoint}/pixel</code>, <em>and</em> starts a bundled <code>fancy-heuristics-js</code> collector that streams interaction events (clicks, scroll, pointer heatmap, dwell — humans and agents) to <code>${endpoint}/collect</code>, keyed by <code>siteKey</code>. Pass <code>data-collect="false"</code> / <code>collect: false</code> for badge + liveness only; omit <code>endpoint</code> and no network request is ever made. The collector is inlined into the IIFE global, so the one external-site <code>&lt;script&gt;</code> is fully self-contained.',
            'how' => 'No build step — drop the one-line tag: <code>&lt;script src="https://unpkg.com/@particle-academy/fancy-pixel/dist/fancy-pixel.global.min.js" data-style="badge" data-mode="floating" data-site="YOUR_SITE_KEY" data-endpoint="https://your-host/heuristics"&gt;&lt;/script&gt;</code>. Or install and mount programmatically: <code>npm i @particle-academy/fancy-pixel</code>, then <code>import { mountPixel } from "@particle-academy/fancy-pixel"; const pixel = mountPixel({ style: "badge", mode: "floating", siteKey: "YOUR_SITE_KEY", endpoint: "https://your-host/heuristics" });</code> — call <code>pixel.destroy()</code> to tear it down. For an inline badge pass <code>mode: "placed"</code> + a <code>target</code> selector/element. <strong>Leave <code>endpoint</code> off</strong> for a pure visual badge with zero network traffic; set it and one embed both verifies the site and streams its interaction analytics to the host (add <code>data-collect="false"</code> for badge + liveness only). Watch presence with <code>document.addEventListener("fancy-pixel:shown", …)</code>.',
        ],

        'fancy-term' => [
            'why' => 'A terminal is where humans and agents do <em>real</em> work — run a command, watch the output, decide what&apos;s next. Most apps embed <code>xterm.js</code> raw: an uncontrolled DOM widget that an embedded agent can only read by scraping pixels and can only drive by faking keystrokes. That breaks the moment the layout shifts. <code>fancy-term</code> makes the terminal a proper Human+ surface — <strong>controlled</strong> so the host owns the buffer, <strong>themeable</strong> so it&apos;s sexy by default, and <strong>bridgeable</strong> so an agent reads the visible buffer and writes input through a stable handle, never the DOM. And because running a command is irreversible, it carries the trust-but-verify affordance: an agent <em>proposes</em> a command and a human confirms before it runs.',
            'what' => 'A React <code>&lt;Terminal&gt;</code> wrapping <a href="https://xtermjs.org/" target="_blank" rel="noopener noreferrer"><code>xterm.js</code></a>. Output is a <strong>controlled buffer</strong> — pass <code>output</code> and the component writes only the appended delta as it grows (so you can stream command output straight from React state, e.g. via fancy-query&apos;s <code>useFancyStream</code>); <code>onData</code> forwards the user&apos;s keystrokes upstream. It carries a stable <code>data-fancy-terminal</code> handle plus a ref exposing a <code>TerminalHandle</code> — <code>write</code> / <code>writeln</code> / <code>clear</code> / <code>reset</code> / <code>fit</code> / <code>focus</code> / <code>getBuffer()</code> (the visible text an agent "sees") / <code>getSelection()</code> / <code>.xterm</code> (escape hatch). Three hooks ship the headless engine layer: <code>useTerminal</code> (create/own the xterm instance), <code>useTerminalFit</code> (ResizeObserver auto-fit, guarding the hidden-tab / late-mount 0×0 trap), and <code>useTerminalSession</code> (bind to a streamed PTY / command backend). <code>xterm</code> + <code>@xterm/addon-fit</code> are <strong>peer dependencies</strong> — the wrapper stays zero-runtime-dep, the same posture as fancy-echarts over ECharts — and a Fancy dark theme (drawn from the react-fancy Tailwind v4 tokens) is the default.',
            'how' => 'Install <code>npm i @particle-academy/fancy-term @xterm/xterm @xterm/addon-fit</code> and import the xterm stylesheet once: <code>import "@xterm/xterm/css/xterm.css";</code>. The parent needs a height (the terminal fits its container): <code>&lt;div style={{ height: 360 }}&gt;&lt;Terminal output={out} onData={(d) =&gt; backend.send(d)} /&gt;&lt;/div&gt;</code>. Drive it from React state via <code>output</code>, or imperatively through the ref. Bind a backend with <code>useTerminalSession({ transport: { send, subscribe } })</code> → <code>&lt;Terminal output={session.output} onData={session.sendData} /&gt;</code>. To make it <em>inhabitable</em>, register the bridge from <code>@particle-academy/agent-integrations</code>: <code>registerTerminalBridge(server, { adapter })</code> exposes <code>terminal_read</code> / <code>terminal_write</code> / <code>terminal_run</code>; turn on <code>pendingMode</code> and destructive commands are staged for a human to confirm (<code>terminal_confirm</code> / <code>terminal_reject</code>). See the <a href="https://xtermjs.org/docs/" target="_blank" rel="noopener noreferrer">xterm.js API docs</a> for the underlying terminal options and addon ecosystem.',
        ],

        'fancy-inertia' => [
            'why' => '<a href="https://inertiajs.com/" target="_blank" rel="noopener noreferrer">Inertia</a> hands a Laravel app a React front end with no API layer — but the seams between Inertia and a real component kit are all friction: where do app-shell providers mount so they survive page swaps, how do server-validation errors reach a controlled input, what touches <code>window</code> and breaks SSR, and how does a navigation feel like more than a hard content swap? <code>fancy-inertia</code> is the bridge that closes every one of those seams for the Fancy UI set, so an Inertia page reads like any other fancy surface.',
            'what' => 'A small set of Inertia ↔ Fancy adapters. <code>&lt;FancyAppRoot&gt;</code> mounts the app-shell providers once (Toast + fancy-screens&apos; ScreenSystem + echarts registration) <em>above</em> the Inertia outlet, so they persist across navigation. <code>useFancyForm()</code> wraps Inertia&apos;s <code>useForm()</code> with a <code>field(name)</code> helper that drops straight into react-fancy inputs, carrying server validation errors. <code>&lt;FancyClientOnly&gt;</code> is the skip-SSR boundary for components that need <code>window</code>. <code>registerFancyComponents()</code> + <code>&lt;InertiaSchemaScreen&gt;</code> turn a Laravel controller into the source of truth for an agent-emitted JSON page. And <code>&lt;FancyPageTransition&gt;</code> is a <strong>zero-dependency, CSS-driven enter/exit page crossfade</strong> keyed on the Inertia page — <code>fade</code> / <code>slide</code> / <code>scale</code> / <code>blur</code> / <code>none</code>; <code>&lt;FancyTransitionProvider&gt;</code> + <code>useFancyTransition()</code> hold and persist the active choice (localStorage) so a live switcher re-scopes every navigation. It snapshots the outgoing page (preserved by key — no remount flash) and honors <code>prefers-reduced-motion</code>.',
            'how' => 'Install <code>npm i @particle-academy/fancy-inertia</code> (peers: <code>@inertiajs/react</code>, <code>react</code>, <code>react-dom</code>, <code>@particle-academy/react-fancy</code>; optional <code>fancy-screens</code> / <code>fancy-echarts</code>). Mount the shell in your Inertia entry: <code>createInertiaApp({ setup: ({ App, props, el }) =&gt; createRoot(el).render(&lt;FancyAppRoot&gt;&lt;App {...props} /&gt;&lt;/FancyAppRoot&gt;) })</code>. For page transitions, wrap <code>&lt;App&gt;</code> once in <code>&lt;FancyTransitionProvider defaultTransition=&quot;fade&quot;&gt;</code> and render the page through <code>&lt;FancyPageTransition pageKey={key}&gt;</code> (App-root render-prop for whole-app coverage, or inside a persistent layout to transition only the body). Build a switcher anywhere with <code>useFancyTransition()</code> + <code>FANCY_TRANSITION_LABELS</code>. This very showcase dogfoods it — the ✨ picker in the top nav.',
        ],

        'fancy-echarts' => [
            'why' => 'Charts are where humans and agents <em>read</em> data together &mdash; the dashboard is the shared surface, so it has to be authorable in seconds and inhabitable by an agent without DOM scraping. <a href="https://echarts.apache.org/" target="_blank" rel="noopener noreferrer">Apache ECharts</a> is the most capable open charting engine on the web, but wiring it into React raw means hand-rolling <code>init</code>/<code>setOption</code>/<code>dispose</code> lifecycles, resize observers, and theme handling on every chart, and bundling the whole engine whether you use it or not. <code>fancy-echarts</code> closes that gap with one terse, typed <code>&lt;EChart&gt;</code> component &mdash; <strong>controlled</strong> via a single <code>option</code> prop and <strong>bridgeable</strong>, so embedded agents drive charts through the <code>chart_*</code> MCP bridge in <code>agent-integrations</code> rather than guessing at the canvas. The chart becomes a proper Human+ surface: terse for authors, stable for agents.',
            'what' => 'The exported surface stays deliberately small. <code>&lt;EChart&gt;</code> is the workhorse &mdash; it accepts the full ECharts <code>option</code> object <em>unchanged</em>, so anything in the <a href="https://echarts.apache.org/en/option.html" target="_blank" rel="noopener noreferrer">ECharts option reference</a> works verbatim, plus React-friendly props for <code>theme</code>, <code>renderer</code>, <code>autoResize</code>, and an <code>onEvents</code> map for <code>click</code>/<code>mouseover</code>/<code>contextmenu</code> handlers. <code>&lt;EChart3D&gt;</code> renders globe, surface, and <code>scatter3D</code>/<code>bar3D</code> series, lazily loading the 3D engine before first paint, and <code>&lt;EChartGraphic&gt;</code> exposes the graphic API for custom drawing. The <code>useECharts</code> hook hands you <code>chartRef</code> and the raw <code>instance</code> for bespoke integrations. Registration is explicit for tree-shaking: <code>registerAll()</code> wires every series at once, while <code>registerCharts([BarChart, LineChart, GridComponent, ...])</code> pulls in only what you render. Four built-in themes ship on top of automatic <code>prefers-color-scheme</code> dark mode. Critically, <code>echarts</code> (and optional <code>echarts-gl</code> for 3D) are <strong>peer dependencies</strong> &mdash; the wrapper bundles <em>zero</em> charting engine, so you control the exact ECharts version and pay for it once.',
            'how' => 'Install with <code>npm install @particle-academy/fancy-echarts</code> (the <code>echarts</code> peer installs automatically on npm 7+ / yarn 3+). Call <code>registerAll()</code> <strong>once per bundle entry</strong>, then the smallest render is a bar chart: <code>&lt;EChart option={{ xAxis: { type: &apos;category&apos;, data: [&apos;Mon&apos;,&apos;Tue&apos;,&apos;Wed&apos;] }, yAxis: { type: &apos;value&apos; }, series: [{ type: &apos;bar&apos;, data: [120, 200, 150] }] }} /&gt;</code>. A line chart is the same shape with <code>series: [{ type: &apos;line&apos;, smooth: true, data: [12, 24, 18] }]</code>, and a donut needs no axes &mdash; <code>series: [{ type: &apos;pie&apos;, radius: [&apos;50%&apos;,&apos;70%&apos;], data: [{ value: 40, name: &apos;A&apos; }, { value: 60, name: &apos;B&apos; }] }]</code>. For 3D, swap to <code>&lt;EChart3D option={{ globe: { baseColor: &apos;#1a3b5c&apos;, viewControl: { autoRotate: true } } }} /&gt;</code>, or drop to raw shapes with <code>&lt;EChartGraphic elements={[{ type: &apos;circle&apos;, shape: { cx: 100, cy: 100, r: 50 }, style: { fill: &apos;#5470c6&apos; } }]} /&gt;</code>. Toggling theme is a prop swap (<code>theme="dark-preset"</code>), and you can <a href="https://echarts.apache.org/examples/en/index.html" target="_blank" rel="noopener noreferrer">browse every chart type</a> to lift an <code>option</code> straight into <code>&lt;EChart&gt;</code>.',
        ],

        'fancy-flow' => [
            'why' => 'Building a workflow editor from scratch on <a href="https://reactflow.dev/" target="_blank" rel="noopener noreferrer">React Flow</a> means wiring nodes, handles, edges, and pan/zoom by hand &mdash; it&apos;s a superb low-level <em>engine</em>, but a steep ramp before you have anything that <em>runs</em>. The alternative is reaching for a heavy closed tool like n8n or Zapier and inheriting someone else&apos;s runtime, hosting, and lock-in. <code>fancy-flow</code> sits in the middle: a batteries-included editor and topological runner you drop into your own React app, owning your graph and your executors. And because it&apos;s built for <strong>Human+ UX</strong>, the editor is <strong>bridgeable</strong> &mdash; the <code>flow_*</code> MCP bridge lets an agent read and mutate the graph through stable node and port ids, <em>never</em> by scraping the DOM &mdash; so humans and agents edit the same workflow together.',
            'what' => '<code>fancy-flow</code> ships a complete editor surface: <code>&lt;FlowCanvas&gt;</code> for the raw canvas, <code>&lt;FlowEditor&gt;</code> as the full editor shell, plus <code>&lt;NodePalette&gt;</code> and <code>&lt;NodeConfigPanel&gt;</code> for adding and configuring nodes. Out of the box you get a six-node kit &mdash; <code>trigger</code>, <code>action</code>, <code>decision</code>, <code>output</code>, <code>note</code>, and <code>subgraph</code> &mdash; covering entry points, work, branching, terminals, annotations, and collapsible groups. Custom nodes are authored with <code>defineNode</code> and <code>&lt;NodePort&gt;</code>, an API that hands you ports, sides, and source/target handles <em>without</em> ever importing from <code>@xyflow/react</code>. That matters because <strong>React Flow is bundled and hidden</strong> inside the dist (its stylesheet included in ours) &mdash; there&apos;s zero peer install and the underlying engine stays swappable. The runtime is real, not just a picture: <code>runFlow</code> does a topological walk firing each node once its upstream ports resolve, and the <code>useFlowRun</code> hook wraps it in React state with per-node status events cycling through <code>idle</code> / <code>queued</code> / <code>running</code> / <code>done</code> / <code>error</code>. State is controlled via <code>useFlowState</code>, and the whole graph is a plain JSON-serializable <code>FlowGraph</code> of nodes and edges &mdash; easy to persist, diff, or emit from an agent. Power users who want to drop to the metal can still consult the <a href="https://reactflow.dev/api-reference" target="_blank" rel="noopener noreferrer">React Flow API reference</a> for the engine underneath.',
            'how' => 'Install the package and import its stylesheet (React Flow&apos;s own CSS rides along inside it): <code>npm install @particle-academy/fancy-flow</code>, then <code>import "@particle-academy/fancy-flow/styles.css"</code>. The smallest render is a controlled <code>FlowGraph</code> on a canvas: <code>const flow = useFlowState(initial)</code> wired into <code>&lt;FlowCanvas nodes={flow.nodes} edges={flow.edges} onConnect={flow.onConnect} /&gt;</code>. To author a custom node, reach for <code>defineNode</code> + <code>&lt;NodePort&gt;</code> &mdash; e.g. <code>const ThresholdNode = defineNode(({ data }) =&gt; (&lt;div className="node"&gt;&lt;NodePort side="left" type="target" id="in" /&gt;&lt;div&gt;&ge; {data.threshold}&lt;/div&gt;&lt;NodePort side="right" type="source" id="pass" /&gt;&lt;/div&gt;))</code> &mdash; no <code>@xyflow/react</code> import in sight. To make the graph <em>run</em>, supply an <code>ExecutorRegistry</code> keyed by node kind and drive it with <code>useFlowRun</code>, then paint live per-node status as each executor resolves. For the concepts beneath the authoring API &mdash; handles, connections, viewport &mdash; <a href="https://reactflow.dev/learn" target="_blank" rel="noopener noreferrer">React Flow&apos;s concepts guide</a> is worthwhile further reading.',
        ],

        'fancy-3d-babylon' => [
            'why' => 'Building production 3D scenes forces a hard choice: pull in a full engine SDK (a multi-megabyte WebGL runtime every visitor downloads) or hand-roll a renderer from scratch. <code>fancy-3d-babylon</code> closes the gap with a turnkey <a href="https://www.babylonjs.com/" target="_blank" rel="noopener noreferrer">Babylon.js</a> adapter that plugs straight into the engine-agnostic <code>@particle-academy/fancy-3d</code> core &mdash; you describe a <em>scene</em>, this package renders it in real WebGL. Crucially, it is a <strong>Human+</strong> surface: children of a <code>&lt;Monitor&gt;</code> render as <em>live, interactive React</em> projected onto a 3D plane &mdash; real DOM with full styling, accessibility, and event handling, not a rasterized texture snapshot. And because <code>fancy-3d</code> exposes the same <code>Scene</code> graph to its <code>scene_*</code> MCP bridge regardless of engine, an agent can position, paint, and rearrange nodes in the scene without ever scraping the canvas.',
            'what' => 'The package layers a WebGL renderer plus React components onto the <code>fancy-3d</code> core. The <code>babylonEngine</code> adapter (from the <code>/engine</code> subpath) mounts a Babylon <code>Engine</code> + <code>Scene</code> onto the core&apos;s <code>&lt;Canvas&gt;</code>, while the <code>/react</code> subpath ships declarative components: <code>&lt;Stage&gt;</code> owns the engine, camera (<code>cameraRadius</code>, <code>cameraTarget</code>, <code>cameraAlpha</code>/<code>cameraBeta</code>), lights, and render loop, and <code>&lt;Monitor&gt;</code> builds a bezel mesh and projects live React children onto it each frame via a <code>matrix3d</code> homography. The root entry adds <code>createBabylonAdapter</code> (painting widgets onto <code>DynamicTexture</code> planes) plus the full layout-helper set &mdash; <code>placeOnGrid</code>, <code>placeOnArc</code>, <code>placeOnWall</code>, <code>placeOnSphere</code>, <code>placeOnPath</code>, and <code>placeOnCylinder</code> &mdash; each mapping a node&apos;s 2D position onto a 3D arrangement, with <code>sceneBounds</code> to compute the extents they need. Every helper mutates the mesh in place, so swapping a globe for a gallery wall is a one-line change. <code>@babylonjs/core</code> is a <strong>peer dependency</strong> &mdash; it is lazy-required only when a Babylon scene actually mounts, so consumers using only the lightweight DOM engine pay zero Babylon bundle cost. The same applies in reverse: <code>@particle-academy/fancy-3d-three</code> mirrors this exact API against the same <code>CanvasEngine</code> interface, so engines are <em>swappable</em> without rewriting your scene. See the <a href="https://doc.babylonjs.com/" target="_blank" rel="noopener noreferrer">Babylon.js documentation</a> for the underlying camera, mesh, and material primitives.',
            'how' => 'Install all three together &mdash; the core, this adapter, and Babylon itself: <code>npm install @particle-academy/fancy-3d @particle-academy/fancy-3d-babylon @babylonjs/core</code>. Mount the engine on the core&apos;s canvas with <code>import { babylonEngine } from "@particle-academy/fancy-3d-babylon/engine"</code> then <code>&lt;Canvas engine={babylonEngine} style={{ height: 480 }} /&gt;</code>. For the declarative React API, the smallest scene is a <code>&lt;Stage&gt;</code> wrapping a <code>&lt;Monitor&gt;</code>: <code>&lt;Stage cameraTarget={[0, 1.5, 0]}&gt;&lt;Monitor position={[0, 1.5, 0]} width={4} height={2.5}&gt;…&lt;/Monitor&gt;&lt;/Stage&gt;</code>. To <em>project live React</em>, drop real components inside &mdash; e.g. a <code>react-fancy</code> <code>&lt;Card&gt;</code> &mdash; and they render as a fully interactive overlay tracked to the mesh, not a flat texture. To arrange many nodes, reach for a layout helper after computing bounds: <code>const b = sceneBounds(scene); placeOnArc(node, mesh, b, { radius: 6, arc: Math.PI })</code> wraps your panels onto a gentle cylinder facing the camera. Swap <code>placeOnArc</code> for <code>placeOnSphere</code> or <code>placeOnWall</code> to restage the same scene without touching node data.',
        ],

        'fancy-3d-three' => [
            'why' => 'Immersive 3D engines almost always abandon everything the DOM is good at &mdash; real text, accessibility, event handling, the React components you already wrote &mdash; the moment you cross into WebGL. <code>fancy-3d</code> refuses that trade: it treats React surfaces and 3D scenes as <em>peers</em>, and its engine-agnostic core (Scene types + a <code>CanvasEngine</code> interface + a DOM/CSS-3D renderer) carries no WebGL dependency at all. This package is the <a href="https://threejs.org/" target="_blank" rel="noopener noreferrer">three.js</a> adapter that lets the <em>same</em> <code>Scene</code> JSON render through a full WebGL renderer &mdash; the same data that paints on DOM or Babylon. That keeps it a proper Human+ surface: a <code>&lt;Monitor&gt;</code> renders <strong>live, interactive React</strong> onto a 3D screen (not a rasterized texture), while agents drive the scene through the <code>scene_*</code> MCP bridge in <code>agent-integrations</code> &mdash; <strong>engine-agnostic</strong>, so neither human nor agent is rewriting anything to switch renderers.',
            'what' => 'The exported surface mirrors the Babylon adapter so engines are swappable, not rebuilt. From <code>@particle-academy/fancy-3d-three/engine</code> you get <code>threeEngine</code>, a <code>CanvasEngine</code> whose <code>EngineHandle.root</code> is the live <code>THREE.Scene</code>. From <code>@particle-academy/fancy-3d-three/react</code> come the declarative components <code>&lt;Stage&gt;</code> (owns the <code>WebGLRenderer</code> + <code>OrbitControls</code> camera + render loop) and <code>&lt;Monitor&gt;</code> (projects a bezel mesh&apos;s corners to screen space each frame and maps a DOM overlay onto the 3D quad via a CSS <code>matrix3d</code> homography), plus the <code>useStage()</code> hook. The package root exports the imperative <code>createThreeAdapter</code> for painting a JSON <code>Scene</code> to textured planes, the <code>sceneBounds</code> helper, the primitive builders (<code>createCard3D</code>, <code>createMonitor</code>, <code>createSign</code>, <code>createPanel</code>, <code>createCurvedPanel</code>, <code>createSphere</code>, <code>createBillboard</code>, <code>createCylinder</code>, &hellip;), and the layout helpers <code>placeOnGrid</code>, <code>placeOnWall</code>, <code>placeOnArc</code> (aliased <code>placeOnCylinder</code>), <code>placeOnPath</code>, and <code>placeOnSphere</code> &mdash; each mutating <code>obj.position</code> / <code>obj.rotation</code> in place. Every primitive, layout, and component name matches <code>fancy-3d-babylon</code>, so a scene authored for one renders recognizably on the other and the two never depend on each other. <code>three</code> is a <strong>peer dependency</strong> &mdash; only consumers actually building 3D scenes install it, so the core stays lightweight for everyone else. The full primitive and option reference lives in the <a href="https://threejs.org/docs/" target="_blank" rel="noopener noreferrer">three.js documentation</a>.',
            'how' => 'Install the three packages together: <code>npm install @particle-academy/fancy-3d @particle-academy/fancy-3d-three three</code> &mdash; none pull in the others. Mount the engine onto the core&apos;s <code>&lt;Canvas&gt;</code>: <code>import { Canvas } from "@particle-academy/fancy-3d"; import { threeEngine } from "@particle-academy/fancy-3d-three/engine";</code> then render <code>&lt;Canvas engine={threeEngine} style={{ height: 480 }} /&gt;</code>. For live React on a 3D screen, the smallest scene is a <code>&lt;Stage&gt;</code> wrapping a <code>&lt;Monitor&gt;</code>: <code>&lt;Stage style={{ height: 520 }}&gt;&lt;Monitor position={[0, 1.6, 0]} width={4} height={2.4}&gt;&lt;Card&gt;…real react-fancy…&lt;/Card&gt;&lt;/Monitor&gt;&lt;/Stage&gt;</code> &mdash; the <code>&lt;Monitor&gt;</code> takes <code>position</code>, <code>width</code>/<code>height</code>, and an optional <code>rotationY</code>. To wrap a JSON <code>Scene</code> onto a curved wall, build meshes with the adapter and place them with a layout helper: <code>const bounds = sceneBounds(scene)</code> then for each node <code>placeOnArc(node, rendered, bounds, { radius: 6 })</code> (swap in <code>placeOnGrid</code>, <code>placeOnSphere</code>, or <code>placeOnPath</code> for other arrangements). Browse the <a href="https://threejs.org/examples/" target="_blank" rel="noopener noreferrer">three.js examples</a> for scene inspiration you can reproduce through the same engine-agnostic API.',
        ],

        'fancy-query' => [
            'why' => 'Every page that reads server state ends up reinventing the same chores: a <code>useState</code>/<code>useEffect</code> fetch chain, a hand-rolled <code>window.Echo</code> listener wired up and torn down by hand, and refetch calls scattered across whatever component happened to mutate the data. <a href="https://tanstack.com/query/latest" target="_blank" rel="noopener noreferrer">TanStack Query</a> already solves caching, deduping, and refetching beautifully &mdash; but it knows nothing about your stack, so the <strong>Inertia</strong> page-prop hydration and the <strong>Laravel Echo</strong> broadcast bridge are still left entirely to you. <code>fancy-query</code> closes exactly that gap: the first render is seeded straight from <code>usePage().props</code> with no fetch, and broadcasts map declaratively onto cache keys. And because the cache keys are <em>deterministic and declarative</em>, they&apos;re agent-legible &mdash; an embedded agent can read precisely which keys a mutation invalidates, making server state a true Human+ surface rather than an opaque tangle of effects.',
            'what' => 'The exports are a thin, honest layer over <a href="https://tanstack.com/query/latest/docs/framework/react/overview" target="_blank" rel="noopener noreferrer">TanStack Query&apos;s React docs</a> surface. <code>&lt;FancyDataRoot&gt;</code> is the mount-once provider &mdash; one <code>QueryClient</code> plus an optional Echo client for the whole app. <code>useFancyQuery(key, fn, options?)</code> is <code>useQuery</code> with an ergonomic signature and full options pass-through, while <code>useFancyMutation({ mutationFn, invalidates })</code> refetches the keys it touched on success &mdash; no repeated <code>invalidateQueries</code> calls. <code>useFancyEchoInvalidation(channel, eventMap)</code> turns a broadcast into a key invalidation declaratively, and <code>useInertiaHydration(map)</code> seeds the cache from Inertia page props so the first paint is already hydrated. The streaming flagship, <code>useFancyStream(key, options)</code>, maps Echo events onto in-place <code>setQueryData</code> reducers &mdash; appending tokens and chat posts instead of refetching &mdash; with an <code>onEvent</code> escape hatch, <code>isStreaming</code> flag, and optional recovery polling. <code>createFancyQueryClient(config?)</code> and <code>FANCY_QUERY_DEFAULTS</code> give you the tuned defaults, override-friendly. Critically, <strong>TanStack Query, React, <code>@inertiajs/react</code>, and Laravel Echo are all peer dependencies</strong> &mdash; nothing is bundled, and an app that touches no data hook tree-shakes the package clean away.',
            'how' => 'Install alongside the peer you&apos;ll always need: <code>npm install @particle-academy/fancy-query @tanstack/react-query</code>. Mount the provider once near your root &mdash; <code>&lt;FancyDataRoot echo={window.Echo}&gt;&lt;App /&gt;&lt;/FancyDataRoot&gt;</code> &mdash; and every hook below shares its client. Hydrate from Inertia props and read in two lines: <code>useInertiaHydration({ tools: [&apos;org-tools&apos;] })</code> then <code>const { data } = useFancyQuery([&apos;org-tools&apos;], () =&gt; api.get(&apos;/api/org/tools&apos;))</code> &mdash; the first render is already populated. Mutate and let the touched keys refetch themselves: <code>useFancyMutation({ mutationFn: p =&gt; api.post(&apos;/api/org/tools&apos;, p), invalidates: [&apos;org-tools&apos;] })</code>. Wire live updates declaratively with <code>useFancyEchoInvalidation(`private-org.${orgId}`, { ToolUpdated: [&apos;org-tools&apos;] })</code>, and for token/SSE streams reach for the realtime-chat pattern &mdash; <code>useFancyStream([&apos;chat&apos;, chatId], { channel: `private-chat.${chatId}`, fetchInitial: () =&gt; api.get(`/api/chat/${chatId}/history`), on: { &apos;post.created&apos;: (cache, e) =&gt; [...(cache ?? []), e.post] } })</code> &mdash; which patches the cache in place so new messages stream in without a refetch.',
        ],

        'fancy-seo' => [
            'why' => 'A Fancy app is an Inertia + React SPA: the browser fills it in <em>after</em> the JavaScript runs. Beautiful for humans &mdash; and invisible to everyone who matters for reach. A search crawler, a social-card scraper, or an <strong>LLM bot</strong> that fetches your URL sees an empty <code>&lt;div id="app"&gt;&lt;/div&gt;</code> on the first byte, so your pages don&apos;t rank, don&apos;t preview as rich cards, and read as blank to the models that increasingly send you traffic. The usual fixes mean either abandoning the SPA or hand-rolling per-route meta in Blade and keeping it in sync with the client forever. <code>fancy-seo</code> closes the gap on the server: it computes the per-route head and renders it into the <em>first byte</em>, so the same app is fully crawlable, shares as a rich card, and is legible to LLMs &mdash; without giving up the SPA.',
            'what' => 'A small, fluent Laravel package. The <code>FancySeo</code> facade resolves a head per request &mdash; <code>defaults([...])</code> for site-wide values, <code>route(&apos;name&apos;, fn ($req) =&gt; [...])</code> for per-route meta, <code>resolveUsing(fn)</code> for a dynamic fallback, <code>for([...])</code> to set it inline from a controller, and <code>noindexRoutes([&apos;admin/*&apos;])</code> to keep private routes out of the index. A single Blade component, <code>&lt;x-fancy-seo::head /&gt;</code>, renders <code>&lt;title&gt;</code>, description, canonical, robots, the full Open Graph + Twitter set, and one <code>&lt;script type="application/ld+json"&gt;</code> per JSON-LD node. It also serves a dynamic <code>sitemap.xml</code> (<code>-&gt;sitemap(fn)</code>), <code>robots.txt</code>, and <code>llms.txt</code> (<code>-&gt;llms(fn)</code>), plus an optional per-page Markdown alternate (<code>-&gt;markdownUsing(fn)</code>). It is the PHP baseline that pairs with <a href="https://www.npmjs.com/package/@particle-academy/fancy-inertia" target="_blank" rel="noopener noreferrer"><code>@particle-academy/fancy-inertia</code></a>&apos;s client <code>&lt;Seo&gt;</code> component &mdash; the server renders the default head, <code>&lt;Seo&gt;</code> overrides it per page via Inertia&apos;s <code>head-key</code> dedupe, so you get exactly one canonical tag, never two.',
            'how' => 'Install with <code>composer require particle-academy/fancy-seo</code>; Laravel auto-discovers the provider + facade. Drop the head into your root Blade <code>&lt;head&gt;</code>: <code>&lt;x-fancy-seo::head /&gt;</code> (above <code>@vite</code> and <code>@inertiaHead</code>). Then teach it your routes in a service provider: <code>FancySeo::defaults([&apos;site_name&apos; =&gt; &apos;Fancy UI&apos;, &apos;image&apos; =&gt; &apos;/og/default.png&apos;])-&gt;route(&apos;packages.show&apos;, fn ($req) =&gt; [&apos;title&apos; =&gt; $req-&gt;route(&apos;package&apos;).&apos; &mdash; Fancy UI&apos;, &apos;canonical&apos; =&gt; $req-&gt;url()])-&gt;noindexRoutes([&apos;admin/*&apos;, &apos;login&apos;]);</code>. Verify the meta is in the raw HTML (not injected after hydration): <code>curl -s https://your.app | grep -i &apos;og:\|canonical\|ld+json&apos;</code>. For the meta to land on the very first byte, turn on SSR (see the SSR page); without it, the <code>fancy-seo</code> Blade baseline is still your crawler floor.',
        ],

        'fancy-heuristics' => [
            'why' => '<strong>End-user optimization, not search-engine optimization.</strong> SEO tunes a page for the crawler; <code>fancy-heuristics</code> tunes it for the people &mdash; and the <em>agents</em> &mdash; actually using it. Off-the-shelf analytics assume a lone human clicking around, but a Human+ app has two kinds of actor on the same surface: a person and an embedded agent trading control. Bolting Google Analytics on top tells you nothing about that, and ships your users&apos; behavior to a third party besides. <code>fancy-heuristics</code> is the self-hosted, first-party server that ingests interaction events from both actors, builds focus heatmaps and session/actor rollups, and verifies the <code>fancy-pixel</code> liveness beacon &mdash; so you can see how your app is actually <em>inhabited</em>, by humans and agents alike, on infrastructure you own.',
            'what' => 'A Laravel package: the server half of the EUO stack. It exposes an event-ingestion endpoint that accepts batched interaction events from <a href="/packages/fancy-heuristics-js"><code>fancy-heuristics-js</code></a> (the browser collector) and the <a href="/packages/fancy-pixel"><code>fancy-pixel</code></a> beacon, persists them via migrations (not just a seeder), and rolls them up into per-session and per-actor summaries plus focus heatmaps (where attention &mdash; clicks, scroll depth, mouse-movement dwell &mdash; actually lands). A facade + Eloquent models give you queryable access to the rollups for your own dashboards, and the <code>fancy-pixel</code> verification confirms a given page genuinely embedded the badge. Human and agent events carry an actor discriminator throughout, so every metric can be sliced by who did it.',
            'how' => 'Install with <code>composer require particle-academy/fancy-heuristics</code> and run <code>php artisan migrate</code> (the schema ships as a migration, so it deploys with the app). Point the browser collector and the verification beacon at the ingest route, then read the rollups from the models in your own analytics views &mdash; e.g. a focus heatmap per route, or an actor breakdown (human vs. agent) per session. Pair it with <code>fancy-heuristics-js</code> on the client and <code>fancy-pixel</code> for the verification badge to get the full GA-style onboarding without giving up first-party ownership of the data.',
        ],

        'fancy-heuristics-js' => [
            'why' => 'The EUO story needs a browser half &mdash; something that watches how a page is actually used and ships those signals home &mdash; but a heavyweight analytics SDK that blocks the main thread or balloons your bundle defeats the point. <code>fancy-heuristics-js</code> is the lightweight, headless collector for <a href="/packages/fancy-heuristics"><code>fancy-heuristics</code></a>: it samples real interaction (clicks, scroll depth, time on page, and mouse-movement focus heatmaps) for both humans and embedded agents, batches it, and flushes via <code>sendBeacon</code> so it never blocks navigation or unload.',
            'what' => 'A tiny, dependency-free TypeScript collector. You initialize it once with your ingest URL; from there it auto-instruments the page &mdash; click and scroll listeners, a time-on-page timer, and a sampled pointer-movement signal that becomes a focus heatmap server-side &mdash; and coalesces everything into batches keyed by an actor discriminator so human and agent activity stay distinguishable. Transport is <code>navigator.sendBeacon</code> with a fetch fallback, so a flush on <code>visibilitychange</code>/unload still lands. No UI, no framework assumptions: it&apos;s the client sensor that feeds the <code>fancy-heuristics</code> server.',
            'how' => 'Install with <code>npm install @particle-academy/fancy-heuristics-js</code> and start it once near your app root: <code>initHeuristics({ endpoint: &apos;/heuristics/ingest&apos; })</code>. That&apos;s the whole integration &mdash; it begins batching interaction events immediately and beacons them to your <code>fancy-heuristics</code> route, where they become session/actor rollups and focus heatmaps. Tag agent-driven actions with the actor field so the server can split human vs. agent behavior.',
        ],

        'fancy-auto-common' => [
            'why' => 'The Human+ contract says every interactive surface must broadcast <em>what changed and who changed it</em>, support undo, and surface presence &mdash; so that coaching, history, and multi-actor awareness compose for free across the whole kit. If each of a dozen <code>fancy-*</code> packages reinvented those primitives, they&apos;d never interoperate. <code>fancy-auto-common</code> is the shared low-level plumbing every Fancy package builds on: one canonical <code>AgentActivity</code> event shape, one presence model, one undo-stack contract, and a handful of effect helpers &mdash; so a bridge in one package and a presence layer in another speak the exact same language.',
            'what' => 'A small, framework-light TypeScript package of shared primitives. It defines the <code>AgentActivity</code> event types + emitter that mutations broadcast (so presence, undo, and coaching layers can subscribe), presence helpers for tracking who is on a surface, the undo-stack primitives that <code>agent-integrations</code>&apos; per-agent <code>agent_undo</code>/<code>agent_redo</code> build on, and effect helpers for the common subscribe/cleanup patterns. It renders nothing &mdash; it&apos;s the connective tissue that lets the rest of the suite stay consistent. Most apps never install it directly: it arrives transitively as a dependency of <code>react-fancy</code>, <code>agent-integrations</code>, and the surface packages.',
            'how' => 'You rarely reach for this one by hand &mdash; it comes in transitively with the packages that use it. If you&apos;re <em>authoring</em> a Fancy-compatible surface and want it to participate in the same activity/presence/undo fabric, install it with <code>npm install @particle-academy/fancy-auto-common</code> and emit the canonical events on mutation: <code>emitAgentActivity({ surface: &apos;sheet&apos;, action: &apos;set-cell&apos;, target, actor })</code>. Subscribers (presence overlays, undo stacks, coaching) then light up automatically because everyone shares this vocabulary.',
        ],

        'mcp-relay-client' => [
            'why' => 'Once a running Fancy app exposes its surface over an <code>agent-integrations</code> relay session, you need something on the other end to actually drive it &mdash; but pulling a full MCP SDK and a runtime just to poke a session URL from a terminal or a CI job is absurd. <code>mcp-relay-client</code> is the opposite: a <strong>single file, zero dependencies</strong>, in whichever of four languages your environment already has &mdash; bash, Python, TypeScript, or Go. Download one, point it at a relay session URL, and you&apos;re listing and calling the host app&apos;s tools.',
            'what' => 'Four hand-written, single-file MCP clients &mdash; <code>connect.sh</code>, <code>connect.py</code>, <code>connect.ts</code>, <code>connect.go</code> &mdash; each speaking the relay&apos;s JSON-RPC-over-SSE transport with nothing but the language&apos;s standard library. Each exposes the same two verbs: <code>tools</code> lists what the connected app offers, and <code>call &lt;tool&gt; &apos;&lt;json-args&gt;&apos;</code> invokes one. It&apos;s the terminal-side counterpart to the <a href="/packages/agent-integrations"><code>agent-integrations</code></a> share relay (e.g. the Agent Playground): the app starts a session, hands you a URL, and this client drives it &mdash; no DOM scraping, no Playwright, just the app&apos;s own MCP tools.',
            'how' => 'Grab just the one you want &mdash; <code>curl -O https://raw.githubusercontent.com/Particle-Academy/mcp-relay-client/main/connect.sh</code> &mdash; then list the host&apos;s tools with <code>bash connect.sh "&lt;session-url&gt;" tools</code> and invoke one with <code>bash connect.sh "&lt;session-url&gt;" call grid_paint &apos;{"x":3,"y":2}&apos;</code>. The <code>.py</code>/<code>.ts</code>/<code>.go</code> files mirror the same interface for whatever runtime you have on hand.',
        ],

        'fancy-app-update' => [
            'why' => 'When you redeploy, every user with the page already open keeps running the <em>old</em> JS/CSS bundle until they happen to refresh &mdash; missing the fix you just shipped and risking subtle mismatches against the new backend. The detector that catches this shouldn&apos;t care what framework you use, so <code>fancy-app-update</code> is deliberately <strong>framework-agnostic</strong>: pure React, no Inertia, no PHP, no backend assumptions. It notices a new build is live and prompts the user to refresh &mdash; with the alert UX and the refresh action both fully yours to customize.',
            'what' => 'A headless hook plus a drop-in component. <code>useAppUpdate(options)</code> detects a new build via one of three strategies in priority order: a custom <code>check</code> you supply, a <code>currentVersion</code> + <code>latestVersion</code> compare, or a zero-config <code>ETag</code>/<code>Last-Modified</code> poll of the page URL &mdash; and it&apos;s SSR-safe, stops polling once it fires, and never false-positives on a network blip. It returns <code>{ updateAvailable, refresh, dismiss, check }</code>. <code>&lt;AppUpdateAlert&gt;</code> is a self-contained prompt (a Portal + inline styles, no UI-library dependency) with Refresh + dismiss, six positions, and a <code>render</code>/<code>children</code> escape hatch to replace the UX entirely. React is the only peer. (<a href="/packages/fancy-inertia"><code>fancy-inertia</code></a> layers an Inertia asset-version &ndash; HTTP 409 &ndash; default on top of this same core, so Laravel apps get detection with zero config.)',
            'how' => 'Install with <code>npm install @particle-academy/fancy-app-update</code> and mount the alert once near your root: <code>&lt;AppUpdateAlert /&gt;</code> &mdash; it renders nothing until an update is detected. Point it at a build signal however you like: zero-config (it polls the current URL&apos;s ETag), a version pair (<code>&lt;AppUpdateAlert currentVersion={BUILD} latestVersion={live} /&gt;</code>), or a custom probe (<code>useAppUpdate({ check: async () =&gt; (await fetch(&apos;/build-id&apos;)).text() !== BUILD })</code>). Customize the action with <code>onRefresh</code>, or replace the whole prompt with <code>render={({ refresh, dismiss }) =&gt; &lt;MyBanner ... /&gt;}</code>.',
        ],

        'fancy-term-host' => [
            'why' => 'A browser <code>&lt;Terminal&gt;</code> is just a view &mdash; the real shell, with its PTY and scrollback, has to live in a Node process somewhere. And for a desktop app, users expect those terminals to <em>survive</em>: a window detach, a full quit, even an auto-update. <code>fancy-term-host</code> is the headless backend that owns that hard part for <a href="/packages/fancy-term"><code>fancy-term</code></a> &mdash; it holds the PTYs (via <code>node-pty</code>) and a tiered persistence engine, behind a handful of injected ports so it stays OS-agnostic and free of any host-framework assumptions.',
            'what' => 'A headless Node package, zero hard third-party deps, built around four injected ports (<code>SettingsProvider</code>, <code>Encryptor</code>, <code>SnapshotStore</code>, <code>HostSpawner</code>) so the connect-or-spawn-or-fall-back logic is core and the host specifics are yours. It ships three persistence tiers &mdash; <strong>T1</strong> snapshot &amp; replay (encrypted, gzipped session state), <strong>T2</strong> retained PTYs that survive a window detach, and <strong>T3</strong> a detached pty-host that survives a full app quit &mdash; spoken over a named pipe (Windows) or unix socket (POSIX) with a versioned wire protocol and a <code>HostClient</code>. The newest piece is the <code>@particle-academy/fancy-term-host/service</code> subpath: run the host as a per-user <strong>OS service</strong> (launchd / systemd&nbsp;--user / Windows scheduled task) on its <em>own</em> standalone Node runtime, so an Electron auto-update never pins the consumer binary &mdash; terminals survive quits <em>and</em> updates. <code>node-pty</code> is the single peer.',
            'how' => 'Install with <code>npm install @particle-academy/fancy-term-host node-pty</code>. For the in-process path, configure the backend and drive it from your host. For survive-everything desktop terminals, reach for the service subpath: <code>const r = await ensureHostService({ label: &apos;academy.particle.app.ptyhost&apos;, userDataDir, runtime: { nodePath: &apos;/opt/app/node&apos; } })</code> &mdash; it installs-if-missing then starts, never throws (inspect <code>r.ok</code>), and falls back gracefully to the detached spawn and then in-process. The browser side connects with the unchanged <code>HostClient</code> either way.',
        ],

        'docs-mcp' => [
            'why' => 'An assistant helping someone build with Fancy UI is only as good as what it knows &mdash; and training data goes stale the day a package ships a new API. Rather than let agents guess from memory (and confidently invent props that don&apos;t exist), <code>docs-mcp</code> serves the live Fancy UI documentation over MCP, so an assistant pulls real usage straight from the source and answers from what the kit actually does today.',
            'what' => 'A small Model Context Protocol server that exposes the suite&apos;s documentation to agents as tools &mdash; search the docs, fetch a package or component&apos;s usage, read the current API. It&apos;s the read-the-docs companion to the install-time registry MCP (which the <a href="https://github.com/Particle-Academy/fancy-ui-plugin" target="_blank" rel="noopener noreferrer">fancy-ui Claude Code plugin</a> bundles): where the registry MCP hands you names + install commands, <code>docs-mcp</code> hands you the prose and examples behind them, so an agent can both <em>find</em> a primitive and <em>learn</em> it without ever scraping a website or guessing.',
            'how' => 'Run it as an MCP server and add it to your agent&apos;s config, or just install the <a href="https://github.com/Particle-Academy/fancy-ui-plugin" target="_blank" rel="noopener noreferrer">fancy-ui plugin</a>, which wires up the hosted registry MCP for you. From there an assistant can answer &ldquo;how do I use <code>&lt;SheetWorkbook&gt;</code>?&rdquo; from the source docs rather than its training cutoff.',
        ],

        'fancy-cli' => [
            'why' => 'There are two honest ways to consume a component, and good teams want the choice. Install the npm package and import it &mdash; clean, updatable, the default. Or <em>own the source</em>: copy the component&apos;s code into your repo so you can read it, fork it, and never wait on an upstream release &mdash; the shadcn-style path. <code>fancy-cli</code> is the second door: <code>npx fancy-cli add &lt;component&gt;</code> vendors the real registry source straight into your project.',
            'what' => 'A source-vendoring command-line tool. <code>npx fancy-cli add &lt;slug&gt;</code> pulls a component&apos;s source bundle from the Fancy UI registry and writes it into your project (landing under <code>src/components/fancy/</code>), resolving its registry + npm dependencies as it goes &mdash; the same registry the <a href="/packages/components">registry MCP</a> and the website&apos;s &ldquo;own the source&rdquo; install tab read from, so what you vendor matches what&apos;s documented. After that the code is <em>yours</em>: edit it freely, no package boundary in the way.',
            'how' => 'No install needed &mdash; run it on demand: <code>npx fancy-cli add card</code> drops the Card source into <code>src/components/fancy/card/</code>, then you import it from your own tree (<code>import { Card } from &apos;@/components/fancy/card&apos;</code>). Prefer the package path instead? Use <code>npm install @particle-academy/react-fancy</code> &mdash; both routes are first-class; <code>fancy-cli</code> exists for when you want to own and tailor the source.',
        ],
    ];

    /**
     * @var array<string, array{why: string, what: string, how: string}>|null
     */
    private static ?array $generated = null;

    /** @return array{why: string, what: string, how: string}|null */
    public static function find(string $packageSlug): ?array
    {
        return self::ENTRIES[$packageSlug] ?? self::generated()[$packageSlug] ?? null;
    }

    /**
     * Lazily load + cache the generated entries from the JSON sidecar.
     *
     * @return array<string, array{why: string, what: string, how: string}>
     */
    private static function generated(): array
    {
        if (self::$generated !== null) {
            return self::$generated;
        }

        $path = resource_path('data/package-context.json');
        if (! is_file($path)) {
            return self::$generated = [];
        }

        $decoded = json_decode((string) file_get_contents($path), true);

        return self::$generated = is_array($decoded) ? $decoded : [];
    }
}
