// Auto-generated registry mapping each dream slug to its lazy-loaded demo component.
// To refresh: copy any new <SlugDemo>.tsx files from the dreaming branch and re-run the
// dreams.json snapshot script.

import { ComponentType, lazy } from "react";

export const dreamDemos: Record<string, ComponentType> = {
  "control-baton": lazy(() => import("./ControlBatonDemo").then(m => ({ default: m.ControlBatonDemo }))),
  "intent-trail": lazy(() => import("./IntentTrailDemo").then(m => ({ default: m.IntentTrailDemo }))),
  "time-scrubber": lazy(() => import("./TimeScrubberDemo").then(m => ({ default: m.TimeScrubberDemo }))),
  "margin-chat": lazy(() => import("./MarginChatDemo").then(m => ({ default: m.MarginChatDemo }))),
  "agent-roster-dock": lazy(() => import("./AgentRosterDockDemo").then(m => ({ default: m.AgentRosterDockDemo }))),
  "briefing-card": lazy(() => import("./BriefingCardDemo").then(m => ({ default: m.BriefingCardDemo }))),
  "pulse-beacon": lazy(() => import("./PulseBeaconDemo").then(m => ({ default: m.PulseBeaconDemo }))),
  "surface-ghost": lazy(() => import("./SurfaceGhostDemo").then(m => ({ default: m.SurfaceGhostDemo }))),
  "streaming-text": lazy(() => import("./StreamingTextDemo").then(m => ({ default: m.StreamingTextDemo }))),
  "suggestion-ghost": lazy(() => import("./SuggestionGhostDemo").then(m => ({ default: m.SuggestionGhostDemo }))),
  "reason-tag": lazy(() => import("./ReasonTagDemo").then(m => ({ default: m.ReasonTagDemo }))),
  "draft-stack": lazy(() => import("./DraftStackDemo").then(m => ({ default: m.DraftStackDemo }))),
  "prompt-input": lazy(() => import("./PromptInputDemo").then(m => ({ default: m.PromptInputDemo }))),
  "magic-wand": lazy(() => import("./MagicWandDemo").then(m => ({ default: m.MagicWandDemo }))),
  "tracked-textarea": lazy(() => import("./TrackedTextareaDemo").then(m => ({ default: m.TrackedTextareaDemo }))),
  "evidence-pane": lazy(() => import("./EvidencePaneDemo").then(m => ({ default: m.EvidencePaneDemo }))),
  "progress-beam": lazy(() => import("./ProgressBeamDemo").then(m => ({ default: m.ProgressBeamDemo }))),
  "whats-new": lazy(() => import("./WhatsNewDemo").then(m => ({ default: m.WhatsNewDemo }))),
  "smart-list": lazy(() => import("./SmartListDemo").then(m => ({ default: m.SmartListDemo }))),
  "mood-meter": lazy(() => import("./MoodMeterDemo").then(m => ({ default: m.MoodMeterDemo }))),
  "annotated-field": lazy(() => import("./AnnotatedFieldDemo").then(m => ({ default: m.AnnotatedFieldDemo }))),
  "beadcrumb": lazy(() => import("./BeadcrumbDemo").then(m => ({ default: m.BeadcrumbDemo }))),
  "hot-zone": lazy(() => import("./HotZoneDemo").then(m => ({ default: m.HotZoneDemo }))),
  "infinite-scroll": lazy(() => import("./InfiniteScrollDemo").then(m => ({ default: m.InfiniteScrollDemo }))),
  "saved-queries": lazy(() => import("./SavedQueriesDemo").then(m => ({ default: m.SavedQueriesDemo }))),
  "keymap-explorer": lazy(() => import("./KeymapExplorerDemo").then(m => ({ default: m.KeymapExplorerDemo }))),
  "waypoint-dots": lazy(() => import("./WaypointDotsDemo").then(m => ({ default: m.WaypointDotsDemo }))),
  "jump-history": lazy(() => import("./JumpHistoryDemo").then(m => ({ default: m.JumpHistoryDemo }))),
  "result-stream": lazy(() => import("./ResultStreamDemo").then(m => ({ default: m.ResultStreamDemo }))),
  "facet-rail": lazy(() => import("./FacetRailDemo").then(m => ({ default: m.FacetRailDemo }))),
  "grouped-tray": lazy(() => import("./GroupedTrayDemo").then(m => ({ default: m.GroupedTrayDemo }))),
  "milestone-empty": lazy(() => import("./MilestoneEmptyDemo").then(m => ({ default: m.MilestoneEmptyDemo }))),
  "time-grid": lazy(() => import("./TimeGridDemo").then(m => ({ default: m.TimeGridDemo }))),
  "classifier-chip": lazy(() => import("./ClassifierChipDemo").then(m => ({ default: m.ClassifierChipDemo }))),
  "batch-preview": lazy(() => import("./BatchPreviewDemo").then(m => ({ default: m.BatchPreviewDemo }))),
  "checklist-rail": lazy(() => import("./ChecklistRailDemo").then(m => ({ default: m.ChecklistRailDemo }))),
  "tour-beacon": lazy(() => import("./TourBeaconDemo").then(m => ({ default: m.TourBeaconDemo }))),
  "empty-canvas": lazy(() => import("./EmptyCanvasDemo").then(m => ({ default: m.EmptyCanvasDemo }))),
  "profile-blanks": lazy(() => import("./ProfileBlanksDemo").then(m => ({ default: m.ProfileBlanksDemo }))),
  "sample-data-toggle": lazy(() => import("./SampleDataToggleDemo").then(m => ({ default: m.SampleDataToggleDemo }))),
  "ticket-spine": lazy(() => import("./TicketSpineDemo").then(m => ({ default: m.TicketSpineDemo }))),
  "sla-pulse": lazy(() => import("./SlaPulseDemo").then(m => ({ default: m.SlaPulseDemo }))),
  "canned-composer": lazy(() => import("./CannedComposerDemo").then(m => ({ default: m.CannedComposerDemo }))),
  "triage-stack": lazy(() => import("./TriageStackDemo").then(m => ({ default: m.TriageStackDemo }))),
  "assist-overlay": lazy(() => import("./AssistOverlayDemo").then(m => ({ default: m.AssistOverlayDemo }))),
  "veto-ribbon": lazy(() => import("./VetoRibbonDemo").then(m => ({ default: m.VetoRibbonDemo }))),
};
